---
paths:
  log_dir: "${HOME}/.devenv/logs"
  backup_dir: "${HOME}/.devenv/backups"
  vscode_config_dir: "${HOME}/.config/Code/User"
  scripts_dir: "${HOME}/Development/scripts"
  development_dirs:
    - "${HOME}/Development/projects"
    - "${HOME}/Development/scripts"
    - "${HOME}/Development/docker"

versions:
  node: "lts"
  python: "3.11"
  docker: "latest"
  nvm: "0.39.0"

packages:
  system:
    - epel-release
    - git
    - curl
    - wget
    - unzip
    - htop
    - vim
    - nano
    - make
    - gcc
    - gcc-c++
    - kernel-devel

  macbook:
    - lm_sensors
    - dmidecode
    - htop
    - cpufrequtils

  python:
    - pip
    - pipenv
    - virtualenv

vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cpptools-themes
    - twxs.cmake
    - ms-vscode.cmake-tools
    - ms-vscode-remote.remote-containers
    - ms-azuretools.vscode-docker
    - william-voyek.vscode-nginx
    - ms-python.vscode-pylance
    - ms-python.python

docker:
  daemon_config:
    default-memory-swap: "1G"
    memory: "8G"
    cpu-shares: 1024
    log-driver: "json-file"
    log-opts:
      max-size: "10m"
      max-file: "3"
