@echo off
setlocal enabledelayedexpansion

REM USD build script for vfx-bootstrap (Windows)
REM This is the primary build target of the project

mkdir build
cd build

cmake "%SRC_DIR%" ^
    -G Ninja ^
    -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%" ^
    -DPXR_ENABLE_PYTHON_SUPPORT=ON ^
    -DPYTHON_EXECUTABLE="%PYTHON%" ^
    -DPXR_USE_PYTHON_3=ON ^
    -DPXR_BUILD_IMAGING=ON ^
    -DPXR_BUILD_USD_IMAGING=ON ^
    -DPXR_BUILD_USDVIEW=ON ^
    -DPXR_BUILD_ALEMBIC_PLUGIN=ON ^
    -DPXR_BUILD_DRACO_PLUGIN=OFF ^
    -DPXR_BUILD_EMBREE_PLUGIN=OFF ^
    -DPXR_BUILD_PRMAN_PLUGIN=OFF ^
    -DPXR_BUILD_DOCUMENTATION=OFF ^
    -DPXR_BUILD_TESTS=OFF ^
    -DPXR_BUILD_EXAMPLES=OFF ^
    -DPXR_BUILD_TUTORIALS=OFF ^
    -DPXR_ENABLE_MATERIALX_SUPPORT=ON ^
    -DMATERIALX_ROOT="%LIBRARY_PREFIX%" ^
    -DPXR_ENABLE_OPENSUBDIV_SUPPORT=ON ^
    -DOPENSUBDIV_ROOT_DIR="%LIBRARY_PREFIX%" ^
    -DPXR_ENABLE_OPENVDB_SUPPORT=ON ^
    -DOPENVDB_ROOT="%LIBRARY_PREFIX%" ^
    -DPXR_ENABLE_PTEX_SUPPORT=ON ^
    -DPTEX_LOCATION="%LIBRARY_PREFIX%" ^
    -DOPENCOLORIO_ROOT="%LIBRARY_PREFIX%" ^
    -DOPENIMAGEIO_ROOT="%LIBRARY_PREFIX%" ^
    -DOPENEXR_LOCATION="%LIBRARY_PREFIX%" ^
    -DTBB_ROOT_DIR="%LIBRARY_PREFIX%" ^
    -DBOOST_ROOT="%LIBRARY_PREFIX%" ^
    -DPXR_BUILD_OPENGL_ENABLED=ON
if errorlevel 1 exit /b 1

cmake --build . --parallel %CPU_COUNT%
if errorlevel 1 exit /b 1

cmake --install .
if errorlevel 1 exit /b 1
