FROM continuumio/miniconda3:latest

# Mount point for local channel
VOLUME ["/home/code/conda-channels:/opt/conda/channels"]

# Copy environment file
COPY environment.yml /tmp/

# Create conda environment
RUN conda env create -f /tmp/environment.yml

# Set default command
CMD ["/bin/bash"]
